version: "3.9"
name: "todo-app"
services:
  ### Databases ###
  # You can run these services by themselves with `docker compose --profile dbs up`
  pg:
    container_name: pg
    image: postgres:alpine
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - $DB_PORT:5432
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    command: postgres -c listen_addresses='*'
    profiles:
      - dbs

  rd:
    container_name: rd
    image: redis:alpine
    volumes:
      - ./.data/redis:/data
    ports:
      - $RD_PORT:6379
    deploy:
      resources:
        limits:
          memory: 64M
    command: redis-server --appendonly yes
    profiles:
      - dbs

